#!/bin/bash -exu

main() {
  local path="$1"
  local password="$2"

  pushd "${path}" > /dev/null
    export OM_TARGET="https://$(terraform output ops_manager_dns)"
    export OM_USERNAME="admin"
    export OM_PASSWORD="${password}"

    om -k configure-authentication -dp "${OM_PASSWORD}"
    om -k configure-director --config <(texplate execute ../ci/assets/template/director-config.yml -f  <(jq -e --raw-output '.modules[0].outputs | map_values(.value)' terraform.tfstate) -o yaml)
  popd > /dev/null
}

main "$@"
