#!/bin/bash -exu

main(){
  local path=${1?"Path is required (e.g. terraforming-pas, terraforming-pks, terraforming-control-plane)"}
  local url

  pushd ${path} > /dev/null
    terraform output ops_manager_ssh_private_key > /tmp/key
    chmod 600 /tmp/key
    url="$(terraform output ops_manager_dns)" 
  popd

  ssh -i /tmp/key "ubuntu@${url}"
}

main "$@"

